name: invoke SECRETS to website

on:
  workflow_dispatch:

jobs:
  run-secrets-js:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: node setup
        uses: actions/setup-node@main
        with:
          node-version: '18'
      # Write secret to JS file, compatible with both browser and Node.js
      - name: LAUNCHADOR🚀
        env:
          IP_INFO_API: ${{ secrets.IP_INFO_API }}
        run: |
          echo "if (typeof window !== 'undefined') { window.ipinfo_api='${IP_INFO_API}'; } const ipinfo_api='${IP_INFO_API}';" > assets/js/secrets.js