name: invoke SECRETS to website

on:
  push:
    branches: ["吉田咲"]
  workflow_dispatch:

jobs:
  run-secrets-js:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: node setup
        uses: actions/setup-node@main
        with:
          node-version: '18'
      - name: dependencies
        run: npm install
      - name: LAUNCHADOR🚀
        env:
          IP_INFO_API: ${{ secrets.IP_INFO_API }}
        run: node assets/js/secrets.js