name: invoke SECRETS to website

on:
  workflow_run:
    workflows: ["Deploy changes to 177013.github.io"]
    types:
      - completed

jobs:
  run-secrets-js:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: node setup
        uses: actions/setup-node@main
        with:
          node-version: '18'
      - name: dependencies
        run: npm install
      - name: LAUNCHADOR🚀
        env:
          IP_INFO_API: ${{ secrets.IP_INFO_API }}
        run: node assets/js/secrets.js